### ISSUE TITLE
Destination file is left open by mergeFiles

### ISSUE THREAD

**Issue by ssallmen** [bhovhannes/junit-report-merger#114]
It seems `mergeFiles` will leave the file in path `destFilePath` open even when it completes the merging. In Windows this is easily seen because the file entry does not disappear from file system even when the `destFilePath` is "deleted" for example using `fs.unlinkSync()`. An example of the actual issue that this will cause is that if mergeFiles is used multiple times to generate different files in a server which runs for a long time, the files will be seen on the file system as long as the server is running, even if they would have been "deleted" by the server using `fs.unlink()` or `fs.unlinkSync()`. There may be also many other issues.

Here is a sample application utilizing mergeFiles that demonstrates the issue easily in Windows. I guess the same issue can be seen also in Unix, for example by checking open files with lsof-command.

```
'use strict';

const fs = require('fs');
const readline = require('readline');
const { create } = require('xmlbuilder2');
const { mergeFiles } = require('junit-report-merger');

function prompt(text) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise(resolve =>
    rl.question(text, () => {
      rl.close();
      resolve();
    })
  );
}

const mergedFilePath = 'merged_junit.xml';
const inputFiles = ['junit_a.xml', 'junit_b.xml'];

inputFiles.forEach((filename, idx) => {
  const xml = create({ version: '1.0' })
    .ele('testsuites', { name: 'My Suites', tests: '1', failures: '0', errors: '0', time: '1.000' })
    .ele('testsuite', { name: `Suite ${idx + 1}`, tests: '1', failures: '0', errors: '0', time: '1.000' })
    .ele('testcase', { classname: 'foo', name: `Test ${idx + 1}`, time: '1.000' })
    .end({ prettyPrint: true });
  fs.writeFileSync(filename, xml);
});

async function main() {
  await mergeFiles(mergedFilePath, inputFiles);
  await prompt(`Merged to file ${mergedFilePath}. Check the file and it's content and press enter to "delete" the merged file using fs.unlinkSync().`);
  console.log(`Now "deleting" file ${mergedFilePath}...`);
  await fs.unlinkSync(mergedFilePath);
  await prompt(
    `File ${mergedFilePath} was now unlinked. You can't read the file anymore, but you will still see it appearing at least in Windows Explorer.\n\
Press enter now to end, and see the file disappearing from the directory listing only after the process finishes.`
  );
}

main()
  .then(() => {
    console.log('Bye!');
  })
  .catch(err => {
    console.log(err);
  });
```

**Comment by ssallmen** [comment]
One example of such "other issue" is that when the file has been left opened by mergeFiles, there is no way for any process to write to the same file path, before the process (for example server) having the open file handles, has been shut down.

**Comment by bhovhannes** [comment]
@ssallmen existing tests do not catch this issue. Can you please verify if version `3.0.2` (just published) works for you ?

**Comment by ssallmen** [comment]
I will test tomorrow but looking at the commit that you used to fix this I would say that it does fix the issue. I was trying similar trial but didn't get it right at first and gave up.

**Comment by ssallmen** [comment]
Thanks @bhovhannes! It does work now. Dest file is not left open anymore by mergeFiles.
