### ISSUE TITLE
mergeFiles callback doesn't seem to get called if there were no errors

### ISSUE THREAD

**Issue by ericmacfa** [bhovhannes/junit-report-merger#12]
I have a js file that contains something like the below code:

``` javascript
var reportMerger = require('junit-report-merger');
var reports = ['./reports/report1.xml', './reports/report2.xml'];

reportMerger.mergeFiles('./final-report.xml', reports, (err) => {
    console.log('DONE');
    if (err) {
        console.log(err);
    } else {
        console.log('Successfully merged all reports into final-report.xml');
    }
});
```

When I run it with node, the files are merged into `final-report.xml` but I don't see anything in stdout (I expected both "DONE" and "Successfully merged all reports into final-report.xml" to print if there are no errors)

Any thoughts on this?

**Comment by bhovhannes** [comment]
Everything seems to be correct. Can you provide `report1.xml` and `report2.xml`, so I can check it locally?

**Comment by joaovieira** [comment]
Looks like `options` is not so optional :)
