### ISSUE TITLE
Help output. 

### ISSUE THREAD

**Issue by Legion112** [bhovhannes/junit-report-merger#178]
Command need a help output to make it easy to use.
```
jrm --help
```
Version 3.0.6
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/20613430/182668064-8187c4d9-5310-4ae9-80b4-4c505e2571b8.png">

**Comment by Legion112** [comment]
Example how it should be

**Comment by bhovhannes** [comment]
Hello 👋 
Published a new version - [4.0.0](https://github.com/bhovhannes/junit-report-merger/releases/tag/v4.0.0). Check it out.
