### ISSUE TITLE
Issue with CircleCI compatibility

### ISSUE THREAD

**Issue by jtneal** [bhovhannes/junit-report-merger#318]
I have a single junit.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="1" failures="0" errors="0" time="0.655">
  <testsuite name="UserMapper" errors="0" failures="0" skipped="0" timestamp="2024-04-13T01:41:56" time="0.598" tests="1">
    <testcase classname="UserMapper should map UserResponse to UserDto" name="UserMapper should map UserResponse to UserDto" time="0.001">
    </testcase>
  </testsuite>
</testsuites>
```

This original file works great with CircleCI, however, if I run it through junit-report-merger, it changes the contents - instead of having a closing tag for the testcase element it changes to a self closing tag, but apparently CircleCI doesn't like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="0" errors="0" skipped="0" time="0.598">
  <testsuite name="UserMapper" errors="0" failures="0" skipped="0" timestamp="2024-04-13T01:41:56" time="0.598" tests="1">
    <testcase classname="UserMapper should map UserResponse to UserDto" name="UserMapper should map UserResponse to UserDto" time="0.001"/>
  </testsuite>
</testsuites>
```

![image](https://github.com/bhovhannes/junit-report-merger/assets/5340961/2f441e14-aebc-4abd-b85f-c704c58b6d9a)

> Test results parsing failed
> junit.xml
> ParseError at [row,col]:[3,5] Message: The element type "testsuites" must be terminated by the matching end-tag "</testsuites>".

Unfortunately, for me, this makes the package unusable because the whole reason I'm generating junit.xml files is to feed them into CircleCI's test results for improved visibility and discoverability of test results and issues. I will also document this issue upstream to CircleCI because, as far as I am aware at least, the self closing tag is entirely allowed in the spec.

Edit:

Using latest version 6.0.3

**Comment by bhovhannes** [comment]
Hello @jtneal, thank you for detailed issue description!

Published fix in https://github.com/bhovhannes/junit-report-merger/releases/tag/v6.0.4

Please share the link to CircleCI issue if you have once. It is very strange they don't support self-closing xml tags.
