### ISSUE TITLE
Empty file as result of mergeFiles

### ISSUE THREAD

**Issue by Xotabu4** [bhovhannes/junit-report-merger#8]
Hi, trying to solve issue with jasmine 2.0 and protractor. When shardingTestFiles with protractor - https://github.com/larrymyers/jasmine-reporters/blob/master/src/junit_reporter.js produces separate xml for each file.

Trying to combine then together with this code:
```javascript
"use strict";

var xmlMerger = require('junit-report-merger');
var fs = require('fs');
var filesList = fs.readdirSync('../testresults');
filesList = filesList.filter(xmlfile=> {
    return xmlfile.includes('store_results_');
});
console.log(filesList);

xmlMerger.mergeFiles('../testresults/store_results.xml', [ 'store_results_test.js.xml',
    'store_results_test2.js.xml',
    'store_results_test3.js.xml' ], (result)=> console.log('OLOLO MERGED!'));
```

As you can see files content is pretty simple - trying on mocked data:
```xml
store_results_test.js.xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="test.js" timestamp="2016-06-01T16:27:47" hostname="localhost" time="2.193" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="test.js" name="1" time="1.745" />
  <testcase classname="test.js" name="2" time="0.15" />
  <testcase classname="test.js" name="3" time="0.147" />
  <testcase classname="test.js" name="4" time="0.147" />
 </testsuite>
</testsuites>

store_results_test2.js.xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="test2.js" timestamp="2016-06-01T16:27:51" hostname="localhost" time="2.171" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="test2.js" name="1" time="1.731" />
  <testcase classname="test2.js" name="2" time="0.15" />
  <testcase classname="test2.js" name="3" time="0.145" />
  <testcase classname="test2.js" name="4" time="0.143" />
 </testsuite>
</testsuites>


store_results_test3.js.xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="test3.js" timestamp="2016-06-01T16:27:54" hostname="localhost" time="2.17" errors="0" tests="4" skipped="0" disabled="0" failures="0">
  <testcase classname="test3.js" name="1" time="1.725" />
  <testcase classname="test3.js" name="2" time="0.151" />
  <testcase classname="test3.js" name="3" time="0.147" />
  <testcase classname="test3.js" name="4" time="0.144" />
 </testsuite>
</testsuites>
```

As a result of executing code above - empty store_results.xml file, and callback (cb) is **NOT** called (no output to console, and no error messages in console)

It looks like issue of code in the library. Any help?

**Comment by Xotabu4** [comment]
Forget about this - wrong paths was passed

**Comment by hleise** [comment]
This seems to be happening to me as well, perhaps I'm missing something?

```
var junitReportMerger = require('junit-report-merger');
var fs = require('fs');
var fileList = fs.readdirSync('./test-reports/e2e/individual-reports').map(function(fileName) {
    return './test-reports/e2e/individual-reports/' + fileName;
});
junitReportMerger.mergeFiles('./test-reports/e2e/e2e-test-report.xml', fileList);
```

The `e2e-test-report.xml` file is successfully created, but it's empty. I double checked the fileList paths and they seem correct. Am I just not properly calling mergeFiles()?

**Comment by hleise** [comment]
I did a little more digging and it looks like `mergeFiles` properly calls `mergeStreams`, but `mergeStreams` never calls `mergeToString`. So the first function in the waterfall runs, but the second one doesn't in `mergeStreams`.

**Comment by hleise** [comment]
I figured it out. I'm using `junit-report-merger` in a protractor config file. For some reason, I need to call `mergeFiles` in the `onPrepare` function as opposed to the `afterLaunch` function. Not entirely sure why, but that's beyond the scope of this repo.

**Comment by Xotabu4** [comment]
@hleise 
Also check order of parameters and callback function position.

`mergeFiles(destFilePath, srcFilePaths, [options], cb)`

Callback must be forth parameter. When using in afterLaunch (docs: https://github.com/angular/protractor/blob/master/lib/config.ts#L500)
You must return promise from function to correctly wait until merging is finished, something like this:
```
afterLaunch: function (exitCode) {
     return new Promise(resolve, reject=> {
          var junitReportMerger = require('junit-report-merger');
          var fs = require('fs');
          var fileList = fs.readdirSync('./test-reports/e2e/individual-reports').map(function(fileName) {
              return './test-reports/e2e/individual-reports/' + fileName;
          });
          junitReportMerger.mergeFiles('./test-reports/e2e/e2e-test-report.xml', fileList, null, err =>{
              if (err) { reject(error) }
              resolve(exitCode)
          });
     })
}

```

Without returning promise from afterLaunch - protractor kills nodejs process before merging and writing to files are done.

**Comment by hleise** [comment]
@Xotabu4 
That worked, thanks!

**Comment by mayur-rawte** [comment]
@Xotabu4 thanks man, you saved my day!
I think it should be mentioned in the docs.
